caldemo_dw:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: gp73525.east-us.azure
      user: DEEPAK_KR
      role: OPENFLOW_ADMIN
      database: FACETS_DEV
      warehouse: OPENFLOW_MERGE_WH
      schema: SILVER
      threads: 4
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
    ci:
      type: snowflake
      account: gp73525.east-us.azure
      user: SVC_DBT_DEV
      role: OPENFLOW_ADMIN
      database: FACETS_CI
      warehouse: OPENFLOW_MERGE_WH
      schema: SILVER
      threads: 4
      private_key_path: "{{ env_var('SNOWFLAKE_PRIVATE_KEY_PATH') }}"
    qa:
      type: snowflake
      account: gp73525.east-us.azure
      user: SVC_DBT_QA
      role: OPENFLOW_ADMIN
      database: FACETS_QA
      warehouse: OPENFLOW_MERGE_WH
      schema: SILVER
      threads: 4
      private_key_path: "{{ env_var('SNOWFLAKE_PRIVATE_KEY_PATH') }}"
    prod:
      type: snowflake
      account: gp73525.east-us.azure
      user: SVC_DBT_PROD
      role: OPENFLOW_ADMIN
      database: FACETS_PROD
      warehouse: OPENFLOW_MERGE_WH
      schema: SILVER
      threads: 4
      private_key_path: "{{ env_var('SNOWFLAKE_PRIVATE_KEY_PATH') }}"
